package app.user.model;

public enum Country {
    ALBANIA, AUSTRALIA, BRAZIL, BULGARIA, CANADA, FRANCE, GERMANY, GREECE, HUNGARY, ITALY,
    JAPAN, KOSOVO, MOLDOVA, NORTH_MACEDONIA, ROMANIA, SERBIA, SPAIN, TURKEY, UNITED_KINGDOM,
}
